### ISSUE TITLE
v5 Roadmap

### ISSUE THREAD

**Issue by g-plane** [bs-community/blessing-skin-server#84]
- [x] Laravel 升级至 v6
- [x] 插件系统：自动识别 `config.blade.php` 为配置页面，无需手动指定
- [x] 插件系统：自动加载在 `package.json` 指定的 ServiceProvider
- [ ] 插件系统：加入 Filters API
- [ ] 插件系统：加入更多事件
- [ ] 在错误页面添加指向 FAQ 的链接
- [ ] 增加“环境信息”页面
- [ ] 增加 OAuth2 Client
- [x] 在根目录放置一个 `index.html` 来提示没有正确设置 Web 根目录的用户

**Comment by tnqzh123** [comment]
@g-plane v4 这才发布多久就决定 v5 的规划了呀…

**Comment by g-plane** [comment]
以下扩展包需要等待其支持 Laravel 6：

- [ ] swiggles/memcache
- [ ] devitek/yaml-translation
- [ ] mews/captcha
- [ ] tymon/jwt-auth
- [x] laravel/passport
- [x] laravel/browser-kit-testing
- [x] laravel/tinker
- [x] barryvdh/laravel-debugbar
- [x] facade/ignition
- [x] beyondcode/laravel-dump-server
- [x] barryvdh/laravel-ide-helper

**Comment by g-plane** [comment]
本 Issue 内容已移到 [Project](https://github.com/bs-community/blessing-skin-server/projects/1).
